sudo: false
os:
  - linux
language: node_js
node_js:
  - '6'
  - '8'
  - '10'
  - '12'
before_install:
  - npm i npminstall
install:	install:
  - npminstall
  - npminstall codecov
script:
  - npm run ci
after_script:
  - codecov
